### ISSUE TITLE
数据来源及可信度

### ISSUE THREAD

**Issue by Charlestar** [CavinHuang/comfyui-nodes-docs#10]
您好，请问这些节点信息的数据都是人工写的吗？感谢对开源社区的贡献！

**Comment by wuqq** [comment]
我也很好奇这么多的帮助文档是怎么来的，如果是人工编撰应该是一个很大的工作量。
想找类似的插件很久了，真的非常感谢作者。

**Comment by CavinHuang** [comment]
人工整理加GPT4-o
