### ISSUE TITLE
我想做贡献

### ISSUE THREAD

**Issue by wibur0620** [CavinHuang/comfyui-nodes-docs#2]
但是下面的那个源代码，我怎么取得，本人对编程不是很熟，我只想丰富节点的解释文档，至于源代码那个，我实在不知道在那么取得，

**Comment by wibur0620** [comment]
还有插件存在一个问题，当在画布中新建一个节点的适合，无法点开解释界面。需要刷新浏览器才行

**Comment by wibur0620** [comment]
https://github.com/CavinHuang/comfyui-nodes-docs/assets/131615326/6fbc2823-54b5-4fc5-98f3-bfad751c1fbf

**Comment by CavinHuang** [comment]
> 但是下面的那个源代码，我怎么取得，本人对编程不是很熟，我只想丰富节点的解释文档，至于源代码那个，我实在不知道在那么取得，

感谢你的反馈

fork之后，需要通过git来去代码到你的本地，然后在docs文件夹下，修改内容或者增加节点类型的文档，通常情况下你能在这里获得所有节点的类型
![截屏2024-05-18 10 55 51](https://github.com/CavinHuang/comfyui-nodes-docs/assets/24950299/77df821e-c8f4-4a37-8366-2d698762fe53)
