### ISSUE TITLE
下面这段源代码是必须的吗？

### ISSUE THREAD

**Issue by wibur0620** [CavinHuang/comfyui-nodes-docs#4]
![image](https://github.com/CavinHuang/comfyui-nodes-docs/assets/131615326/cbc371f3-d8a5-4a1f-bbc0-803e85c6b11b)
如图所示，这段代码是必须的吗？因为我不知道怎么找到这段代码，
目前我能找到所有节点的原始数据，(比如位置，名称等)
![image](https://github.com/CavinHuang/comfyui-nodes-docs/assets/131615326/abd882f1-f141-4425-8ea2-c8807006ec63)
如果文档最后那段源代码，还有如图每个参数解释后面的东西不是必须的，那我这边就不写这些额外的东西了？
![image](https://github.com/CavinHuang/comfyui-nodes-docs/assets/131615326/88fd6467-f99f-4a83-ab59-a9f143b481ac)

**Comment by CavinHuang** [comment]
这段代码，通常可以从作者插件github地址中找到，这段代码有利于有代码基础的朋友，对这个插件的理解，当然如果实在找不到可以先留空
