### ISSUE TITLE
功能请求~

### ISSUE THREAD

**Issue by ghostrunner-art** [CavinHuang/comfyui-nodes-docs#6]
这个节点文档功能非常好，感谢您对开源社区做的贡献。

现在想请求一个功能。
这个文档只有很少的comfyui官方的文档，大量的插件节点是没有文档的。想请求的功能是这样，对于任何节点的文档，用户都可以自己编辑里面的内容，并保存在本地（最好能有说明文档的导入或者导出功能，方便携带）。
未来，用户可以将自己对节点的说明保存在云端，方便更多的人查看comfy的节点。

以下来自谷歌翻译（The following is from Google Translate）
This node documentation function is very good, thank you for your contribution to the open source community.

Now I want to request a feature.
There are only a few official comfyui documents for this document, and a large number of plug-in nodes have no documentation. The function I want to request is this. For any node document, users can edit the content themselves and save it locally (it is best to have the import or export function of the description document for easy portability).
In the future, users can save their node descriptions in the cloud to facilitate more people to view comfy nodes.

**Comment by CavinHuang** [comment]
感谢您的建议。

目前正有这个规划，具体的交互还在考量中，并且还希望用户可以更好的参与完善节点文档。

**Comment by ghostrunner-art** [comment]
![1](https://github.com/CavinHuang/comfyui-nodes-docs/assets/7589642/eee703c9-c108-4ce6-96d5-ababa3e9cc04)

可以先在图中红框部分加入编辑和保存功能。这样方便普通用户在本地备注节点功能特色（包括输入、输出、特点、应用场景等），之后的版本再加入导入、导出功能以及云端等功能。
据观察，目前很多复杂的工作流没有很好的备注，原因可能是官方的note用起来太麻烦，又不清晰。您的插件可以在一定程度上，从根源上解决这方面问题。

十分期待您的更新。

**Comment by CavinHuang** [comment]
最新版本已经更新了

- 在设置中增加了开关，可以选择是否显示节点的文档
- 增加文档本地修改功能，如果觉得文档有问题，可以在本地修改，不会影响到其他人
- 在设置中增加了是否参与共建的开关，可以选择是否参与共建，默认打开，打开后会把本地修改的记录，记录到云DB上，后期经过审核后会合并到主分支上
- 增加导出文档和导入文档功能，导出文档会把本地修改的记录和仓库提供的文档导出下载，导入文档会把导出的文档导入到本地，不会影响主仓库的文档。
- 修复了一些bug

**Comment by wibur0620** [comment]
我是否可以借用您的代码重开一个仓库？

**Comment by wibur0620** [comment]
> 我是否可以借用您的代码重开一个仓库？

因为我认为这种类型的插件，单靠用爱发电，肯定是跟不上节点更新换代速度的。到最后会出现节点文档内容与实质不符，形成误导，对用户来说，出现这种情况，会导致对插件的依赖度和信赖度都会降低。
我的想法是，我使用您的代码，重开一个仓库，在那个仓库，主要服务对象为零基础毫无代码基础的纯新手（和您这边的区别在于您这边可以为每个插件贡献节点的源代码。方便有代码基础的用户理解节点。而我那边将不提供节点源代码）
我会在新开的项目页面做引导，将有代码基础的用户引导到您这边。
以上是表面上新仓和您这边的区别。
重点是我认识到要成功将此插件铺开并且内容完善，需要强有力的运营才行，而这点，我可以做到。到时候节点文档我们共享。你这边只需要添加节点源代码（因为到时候我那边提供的文档不在有源代码）
也就是说，我们形成两个分支，您这边负责专业用户，懂代码的用户，我那边纯负责小白。然后我们的节点文档共享。
在运营上。我已经有初步的方案了，为了形成共创，我的设计会照顾到每个贡献者的利益，我相信利益能成功驱动此插件成长和完善。
对此，我征求您的同意。
